baseURL = "https://awalpremi.github.io/aeio/"
languageCode = "en-us"
title = "aeio games"
theme = "PaperMod"

[params]
  author = "Melissa"
  description = "A description of your site for SEO."
  defaultTheme = "Dark"  # Light/Dark theme auto-switching
  disableSearch = true  # Enable built-in search
  mainSections = []
  ShowShareButtons = true
  disableSpecial1stPost = true
  hideMeta = true
  ShowBreadCrumbs = true
 hideSummary = true


[params.label]
  icon = "images/logo.svg"
  iconHeight= 75

[params.assets]
  favicon = "images/favicon.png"
  apple_touch_icon =  "images/favicon.png"


[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

