baseURL = "https://a-e-i-o.com/"
languageCode = "en-us"
title = "a-e-i-o"
theme = "PaperMod"

[params]
  author = "Melissa"
  description = "A description of your site for SEO."
  defaultTheme = "Light"  # Light/Dark theme auto-switching
  disableSearch = true  # Enable built-in search
  mainSections = []
  ShowShareButtons = true
  


[params.label]
  icon = "images/aeio-logo.png"

[params.assets]
  favicon = "images/favicon.png"


[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
