baseURL = "https://a-e-i-o.com"
languageCode = "en-us"
title = "aeio games"
theme = "PaperMod"

[params]
  author = "Melissa"
  description = "Pixel adventure and narrative games"
  defaultTheme = "dark"  # Light/Dark theme auto-switching
  disableSearch = true  # Enable built-in search
  mainSections = []
  ShowShareButtons = true
  disableSpecial1stPost = true
  hideMeta = true
  ShowBreadCrumbs = true
 hideSummary = true
 inlineStyle = true
   inlineScript = true
     minify = true


[services.googleAnalytics]
  ID = "G-GXVBXGX2ZL"


[params.label]
  icon = "images/logo.svg"
  iconHeight= 75

[params.assets]
  favicon = "images/favicon.png"
  apple_touch_icon =  "images/favicon.png"


[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Enable Caching
[outputs]
  home = ["HTML", "RSS", "JSON"] # Optimize output formats

# Specify Build Options
[build]
  writeStats = true  